### ISSUE TITLE
에러 구문

### ISSUE THREAD

**Issue by HO-Gan** [hands8142/bot#1]
관리자 권한이 없어서 출력되는 오류 구문은

@bot.event
async def on_command_error(ctx, error):
    mention = ctx.message.author.mention
    if isinstance(error, MissingPermissions):
        await ctx.send(f"{mention}, 권한이 없습니다!")

굳이 명령어 하나하나에 다 에러를 작성하지 않고, 이런식으로 하나의 이벤트로 다 묶을 수 있지 않을까요

**Comment by hands8142** [comment]
cogs 에서 작동이 안됩니다 더 자세하게 가능합니까cogs 에서 쓰는 방법을 모르겠습니다

**Comment by HO-Gan** [comment]
사실 저도 cog를 통해 작성을 하지 않아서 cog내에서 에러를 하나로 묶는건 모르겠네요...

**Comment by hands8142** [comment]
그럼 나중에 아시며는 저도 알려주세요 그럼 이 이슈는 닫겠습니다
